#!/bin/sh

cd ~/my/compiled

if test -d create_ap
then true
else git clone --recursive 'https://github.com/oblique/create_ap'
fi

cd create_ap

# sudo systemctl stop wpa_supplicant.service
eval $(my-require bash.guix util-linux.guix procps.guix hostapd.nix hostapd.guix iproute2.guix iw.guix dnsmasq.nix dnsmasq.guix iptables.guix)

sudo herd stop networking # network manager hungs on guix

sudo ./create_ap wlo1 wlo1 AndroidAP2372 Android1

sudo herd start networking

# if ! which create_ap >/dev/null
# then
# 	echo 'create_ap not installed, read this:' 1>&2
# 	echo 'https://askubuntu.com/a/1062026' 1>&2
# 	echo 'and this:' 1>&2
# 	echo 'https://github.com/oblique/create_ap' 1>&2
# 	exit 1
# fi

# exec my-root-do create_ap wlo1 wlo1 AndroidAP_2372 Android1
