#!/bin/sh -x

FILE=filename
OUT="$FILE"
#### Note: out will end with ".tar" or ".tar.gz" or ".tar.enc" or even ".tar.gz.enc"

COMPRESS=yes
# COMPRESS=no

ENCRYPT=yes
# ENCRYPT=no

TAR_OPTS=

### always archiving
OUT="$OUT.tar"

case $COMPRESS in
	yes)
		OUT="$OUT.gz"
		COMPRESSCMD=gzip
		;;
	no)
		COMPRESSCMD=cat
		;;
	*)
		echo "WTF 1" ; exit 1
		;;
esac

#### Note: progress is only reported for compression
PROGRESSCMD="pv --wait --size $(du -sb "$FILE" | awk '{ print $1 }')"

case $ENCRYPT in
	yes)
		tar -c $TAR_OPTS -f - "$FILE" \
			| $PROGRESSCMD \
			| $COMPRESSCMD \
			| openssl enc -aes-256-cbc -in - \
			> "$OUT.enc"
		;;
	no)
		tar -c $TAR_OPTS -f - "$FILE" \
			| $PROGRESSCMD \
			| $COMPRESSCMD \
			> "$OUT"
		;;
	*)
		echo "WTF 2" ; exit 1
		;;
esac


