#!/bin/sh -x

FILE=filename.tar.gz.enc
# NOTE! OUTPUTS TO CURRENT DIRECTORY!

TAR_OPTS=

if echo "$FILE" | grep -q -e ".tar.gz"
then TAR_OPTS="$TAR_OPTS -z"
fi

PROGRESSCMD="pv --wait --size $(du -sb "$FILE" | awk '{ print $1 }')"

case "$FILE" in
	*.enc)
		openssl enc -d -aes-256-cbc -in "$FILE" | \
			$PROGRESSCMD | \
			tar -x $TAR_OPTS
		;;
	*)
		tar -x $TAR_OPTS -f "$FILE"
		;;
esac


