#! /bin/sh

while read FILE
do
	case "$FILE" in
		/*) ;;
		*) FILE="$PWD/$FILE" ;;
	esac
	case "$1" in
		"C-d")
			my-safe-rm "$FILE"
			notify-send "Removed '$FILE'"
			;;
		"C-y")
			printf "%s" "$FILE" | xclip -selection clipboard
			notify-send "Copied '$FILE'"
			;;
		"C-s")
			ESC="$(my-escape-name "$FILE")"
			x-terminal-emulator-exe "my-save $ESC"
			;;
		"C-w")
			nitrogen --save --set-zoom-fill "$FILE" ;;
	esac
done
